import type { BlogPost } from "@/lib/blog-types";

function u(id: string): string {
  return `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=80`;
}

function p(a: string, b: string, c: string): string[] {
  return [a, b, c];
}

/** Contenu éditorial : 15 articles par pôle (Digital, IT, Solutions). */
export const BLOG_POSTS: BlogPost[] = [
  // --- IT (15) ---
  {
    slug: "cybersecurite-entreprise-2026",
    title: "Cybersécurité en entreprise : les priorités pour 2026",
    pole: "it",
    excerpt:
      "Cartographie des risques, MFA, sauvegardes testées et culture sécurité : le socle à renforcer avant d’investir dans les outils.",
    readMinutes: "7 min",
    publishedAtLabel: "8 janvier 2026",
    publishedAtIso: "2026-01-08",
    imageSrc: u("photo-1563986768609-322da13575f3"),
    imageAlt: "Professionnelle travaillant sur la sécurité informatique",
    body: p(
      "Les équipes IT voient la surface d’attaque s’élargir avec le télétravail, le SaaS et l’IA générative : une politique de mots de passe unique ne suffit plus. La priorité est une gouvernance claire (qui décide, qui alerte, qui restaure) et des contrôles mesurables.",
      "La double authentification (MFA) sur les comptes sensibles, la segmentation réseau et la journalisation centralisée restent les trois leviers au meilleur rapport effort / réduction de risque pour une PME ou une ETI.",
      "Enfin, les sauvegardes ne valent que si elles sont testées : un plan de reprise annuel, chronométré, évite les mauvaises surprises le jour où un ransomware frappe.",
    ),
  },
  {
    slug: "infogerance-sla-comment-choisir",
    title: "Infogérance : comment lire un SLA et choisir son prestataire",
    pole: "it",
    excerpt:
      "Disponibilité, temps d’intervention, périmètre d’astreinte et exclusions : les clauses à comparer ligne à ligne avant de signer.",
    readMinutes: "6 min",
    publishedAtLabel: "22 janvier 2026",
    publishedAtIso: "2026-01-22",
    imageSrc: u("photo-1558494949-ef010cbdcc31"),
    imageAlt: "Baie serveurs et câblage réseau en datacenter",
    body: p(
      "Le SLA (accord de niveau de service) traduit l’engagement du prestataire en indicateurs chiffrés : taux de disponibilité cible, délais de prise en charge (TTR) et de résolution (TTR max), souvent différenciés selon la criticité des incidents.",
      "Méfiez-vous des SLA « 99,9 % » sans fenêtre de maintenance définie ni précision sur ce qui est mesuré (uniquement le lien internet ou bien l’ensemble des services métiers hébergés ?).",
      "Un bon contrat précise aussi les canaux d’escalade, les rapports mensuels fournis et les pénalités ou crédits en cas de manquement répété — c’est le seul moyen d’aligner les intérêts sur la durée.",
    ),
  },
  {
    slug: "it-mdm-postes-sensibles",
    title: "MDM : sécuriser les postes sensibles sans brider les équipes",
    pole: "it",
    excerpt: "Profils, apps autorisées, chiffrement et perte/vol : le équilibre entre contrôle et productivité.",
    readMinutes: "6 min",
    publishedAtLabel: "28 janvier 2026",
    publishedAtIso: "2026-01-28",
    imageSrc: u("photo-1517694712202-14dd9538aa97"),
    imageAlt: "Développeur travaillant sur ordinateur portable",
    body: p(
      "Un MDM bien réglé commence par la cartographie des usages : qui a besoin d’admin local, quelles applications sont indispensables, et quels risques accepte la direction.",
      "Les profils iOS/Android et Windows/macOS convergent vers les mêmes principes : moindre privilège, chiffrement disque, blocage des sideloads non validés et wipe à distance en cas de perte.",
      "La clé d’adoption est la communication : expliquer le « pourquoi » des restrictions limite le contournement et le shadow IT.",
    ),
  },
  {
    slug: "it-sauvegarde-immutable-ransomware",
    title: "Sauvegardes immuables : l’assurance anti-ransomware à ne pas négliger",
    pole: "it",
    excerpt: "Copies WORM, air gap et tests de restauration : comment tenir une ligne de défense crédible.",
    readMinutes: "6 min",
    publishedAtLabel: "4 février 2026",
    publishedAtIso: "2026-02-04",
    imageSrc: u("photo-1544197150-b99a580bb7a8"),
    imageAlt: "Infrastructure serveurs et stockage",
    body: p(
      "Les attaquants ciblent désormais systématiquement les dépôts de sauvegarde : une stratégie crédible combine copies immuables, rétention courte sur site et copies offline ou cloud object lock.",
      "La fréquence des snapshots doit être alignée sur le RPO métier ; les bases transactionnelles nécessitent souvent des agents applicatifs plutôt que de simples copies de fichiers.",
      "Sans tests de restauration chronométrés, le meilleur plan reste théorique : programmez des exercices trimestriels et documentez les écarts.",
    ),
  },
  {
    slug: "it-microsoft-365-gouvernance",
    title: "Microsoft 365 : gouvernance des groupes, Teams et SharePoint",
    pole: "it",
    excerpt: "Naming, durée de vie des espaces et archivage : éviter l’explosion des sites orphelins.",
    readMinutes: "5 min",
    publishedAtLabel: "11 février 2026",
    publishedAtIso: "2026-02-11",
    imageSrc: u("photo-1633265486064-086b219458ec"),
    imageAlt: "Interface collaborative sur écran",
    body: p(
      "Teams et SharePoint se déploient vite ; sans règles, les espaces se multiplient et la recherche devient inutilisable.",
      "Des conventions de nommage, des modèles approuvés et des politiques d’expiration pour les groupes Microsoft 365 réduisent fortement la dette documentaire.",
      "Les administrateurs bénéficient d’outils d’inventaire et de rapports d’activité pour identifier les sites inactifs avant archivage.",
    ),
  },
  {
    slug: "it-soc-leger-pme",
    title: "SOC managé « léger » : quand la détection 24/7 devient accessible",
    pole: "it",
    excerpt: "Corrélations, playbooks et astreinte : ce qu’un SOC externalisé peut couvrir pour une ETI.",
    readMinutes: "7 min",
    publishedAtLabel: "19 février 2026",
    publishedAtIso: "2026-02-19",
    imageSrc: u("photo-1555949963-aa79dcee981c"),
    imageAlt: "Analyse de données de sécurité sur moniteurs",
    body: p(
      "Un SOC managé n’impose pas d’investir dans un SIEM maison : les fournisseurs mutualisent les corrélations et les signatures sur des périmètres homogènes.",
      "Les playbooks d’escalade doivent être co-écrits avec vos métiers : qui valide un isolement réseau, qui autorise un wipe poste ?",
      "Mesurez le SOC sur le temps de détection, le taux de faux positifs et la qualité des comptes rendus — pas seulement sur le volume d’alertes traitées.",
    ),
  },
  {
    slug: "it-vpn-zero-trust",
    title: "Au-delà du VPN : accès conditionnel et segmentation des utilisateurs",
    pole: "it",
    excerpt: "Posture device, MFA et micro-segmentation pour réduire la confiance implicite du réseau « interne ».",
    readMinutes: "6 min",
    publishedAtLabel: "26 février 2026",
    publishedAtIso: "2026-02-26",
    imageSrc: u("photo-1451187580459-43490279c0fa"),
    imageAlt: "Carte réseau et connectivité mondiale",
    body: p(
      "Le VPN classique recrée un tunnel large vers le LAN : en cas de compromission d’un poste, l’attaquant hérite souvent d’un accès trop large.",
      "L’accès conditionnel relie identité, appareil et contexte (lieu, heure) pour n’ouvrir que les applications nécessaires.",
      "La micro-segmentation complète la logique en limitant les flux est-ouest entre serveurs, même « à l’intérieur » du datacenter.",
    ),
  },
  {
    slug: "it-cloud-hybride-couts",
    title: "Cloud hybride : maîtriser les coûts et les dépendances fournisseurs",
    pole: "it",
    excerpt: "Réservations, tags de facturation et sortie de données : une grille de lecture pour la direction financière.",
    readMinutes: "6 min",
    publishedAtLabel: "5 mars 2026",
    publishedAtIso: "2026-03-05",
    imageSrc: u("photo-1544197150-b99a580bb7a8"),
    imageAlt: "Infrastructure cloud et serveurs",
    body: p(
      "Les factures cloud explosent souvent par manque de discipline : instances oubliées, stockages non lifecyclés et egress non budgétisés.",
      "Le tagging obligatoire par centre de coût et l’automatisation d’arrêt des environnements de test hors heures ouvrées sont des quick wins.",
      "Anticipez la sortie d’un fournisseur : formats exportables, conteneurs et IaC réduisent le lock-in technique.",
    ),
  },
  {
    slug: "it-journaux-rgpd",
    title: "Journalisation SI et RGPD : durées, finalités et minimisation",
    pole: "it",
    excerpt: "Quels logs conserver, comment pseudonymiser et qui peut consulter les traces d’accès.",
    readMinutes: "5 min",
    publishedAtLabel: "12 mars 2026",
    publishedAtIso: "2026-03-12",
    imageSrc: u("photo-1504384308090-c894fdcc538d"),
    imageAlt: "Clavier et écran affichant du code",
    body: p(
      "Les journaux sont à la fois un outil de sécurité et un traitement de données personnelles lorsqu’ils capturent des identifiants ou des contenus.",
      "Fixez des durées de conservation proportionnées, limitez l’accès aux équipes habilitées et documentez les finalités (sécurité, support, conformité).",
      "La pseudonymisation et la rotation des clés de chiffrement des archives de logs réduisent l’exposition en cas de fuite.",
    ),
  },
  {
    slug: "it-kubernetes-exploitation",
    title: "Kubernetes en production : exploitation et sauvegardes applicatives",
    pole: "it",
    excerpt: "États persistants, upgrades de cluster et stratégie de restore : la check-list ops.",
    readMinutes: "7 min",
    publishedAtLabel: "18 mars 2026",
    publishedAtIso: "2026-03-18",
    imageSrc: u("photo-1558494949-ef010cbdcc31"),
    imageAlt: "Salle serveurs et baies informatiques",
    body: p(
      "Kubernetes simplifie le déploiement mais complexifie l’observabilité : métriques, traces et logs doivent être centralisés dès le premier cluster.",
      "Les volumes persistants nécessitent des solutions de backup CSI-aware ; un snapshot SAN seul ne garantit pas la cohérence applicative.",
      "Planifiez les fenêtres d’upgrade du plan de contrôle et testez la compatibilité des CRD opérateurs avant toute montée de version majeure.",
    ),
  },
  {
    slug: "it-identity-governance",
    title: "Gouvernance des identités : revues d’accès et comptes privilégiés",
    pole: "it",
    excerpt: "Campagnes de certification, PAM et JIT : réduire la surface des comptes à tout faire.",
    readMinutes: "6 min",
    publishedAtLabel: "24 mars 2026",
    publishedAtIso: "2026-03-24",
    imageSrc: u("photo-1563986768609-322da13575f3"),
    imageAlt: "Sécurité des accès et authentification",
    body: p(
      "Les comptes administrateur partagés sont une cause fréquente d’incidents non traçables : privilégiez les comptes nominatifs et le JIT (just-in-time).",
      "Les revues d’accès trimestrielles doivent impliquer les managers métiers, pas uniquement l’IT.",
      "Un inventaire des applications SaaS et de leurs owners métier évite les abonnements fantômes et les accès orphelins.",
    ),
  },
  {
    slug: "it-wifi-entreprise-8021x",
    title: "Wi-Fi d’entreprise : 802.1X, certificats et expérience utilisateur",
    pole: "it",
    excerpt: "Radius, SCEP et onboarding mobile : sécuriser le sans-fil sans helpdesk saturé.",
    readMinutes: "5 min",
    publishedAtLabel: "30 mars 2026",
    publishedAtIso: "2026-03-30",
    imageSrc: u("photo-1544197150-b99a580bb7a8"),
    imageAlt: "Équipement réseau et connectivité",
    body: p(
      "Le WPA2-Entreprise avec 802.1X reste le standard pour séparer visiteurs, IoT et postes corporate sur des VLAN distincts.",
      "La gestion des certificats clients sur macOS/iOS nécessite une PKI comprise et des profils MDM cohérents.",
      "Mesurez la qualité radio (RSSI, retries) plutôt que le débit théorique annoncé sur la fiche du matériel.",
    ),
  },
  {
    slug: "it-postgresql-ha",
    title: "PostgreSQL haute disponibilité : Patroni, réplication et PITR",
    pole: "it",
    excerpt: "Failover automatique, backups WAL et tests de reprise pour bases métier critiques.",
    readMinutes: "7 min",
    publishedAtLabel: "6 avril 2026",
    publishedAtIso: "2026-04-06",
    imageSrc: u("photo-1544383835-bda2bc66a55d"),
    imageAlt: "Base de données et stockage",
    body: p(
      "La réplication synchrone vs asynchrone est un compromis entre RPO zéro et latence inter-sites.",
      "Patroni (ou équivalent) apporte élection de leader et bascule, à condition d’avoir un quorum etcd solide.",
      "Combinez snapshots et archives WAL pour permettre un retour à un point dans le temps précis après une erreur humaine.",
    ),
  },
  {
    slug: "it-sensibilisation-phishing",
    title: "Sensibilisation phishing : au-delà du taux de clic simulé",
    pole: "it",
    excerpt: "Scénarios progressifs, feedback immédiat et culture de signalement sans « naming & shaming ».",
    readMinutes: "5 min",
    publishedAtLabel: "9 avril 2026",
    publishedAtIso: "2026-04-09",
    imageSrc: u("photo-1563013544-824ae1b704d3"),
    imageAlt: "Sécurité informatique et protection des données",
    body: p(
      "Les campagnes trop agressives érodent la confiance : alternez simulations et micro-formations de deux minutes intégrées au workflow.",
      "Récompensez le signalement d’emails suspects plutôt que de sanctionner les clics sur une fausse alerte isolée.",
      "Corrélez les résultats avec les incidents réels pour ajuster les scénarios aux métiers les plus exposés.",
    ),
  },
  {
    slug: "it-observabilite-opentelemetry",
    title: "Observabilité : OpenTelemetry pour corréler logs, métriques et traces",
    pole: "it",
    excerpt: "Instrumentation progressive, sampling et coûts de stockage : une feuille de route pragmatique.",
    readMinutes: "6 min",
    publishedAtLabel: "12 avril 2026",
    publishedAtIso: "2026-04-12",
    imageSrc: u("photo-1551434678-e076c223a692"),
    imageAlt: "Équipe technique devant plusieurs écrans",
    body: p(
      "OpenTelemetry standardise l’instrumentation côté applications et agents, réduisant le lock-in sur un fournisseur APM unique.",
      "Le sampling des traces est indispensable pour maîtriser le volume en production tout en conservant les erreurs et latences p95.",
      "Alignez la rétention sur les besoins réels de debug vs conformité ; tout ne doit pas être conservé dix ans.",
    ),
  },

  // --- Digital (15) ---
  {
    slug: "refonte-site-b2b-cles-reussite",
    title: "Refonte d’un site B2B : cinq clés pour ne pas rater l’exercice",
    pole: "digital",
    excerpt:
      "Objectifs métiers, contenus, performance Web et intégration CRM : la checklist avant le premier maquettage.",
    seoDescription:
      "Refonte site B2B : fixer les objectifs métiers, auditer les contenus et le SEO, viser les Core Web Vitals et préparer l’intégration CRM avant de lancer les maquettes.",
    keywords: [
      "refonte site B2B",
      "UX",
      "Core Web Vitals",
      "migration SEO",
      "intégration CRM",
      "performance web",
      "stratégie contenu",
    ],
    readMinutes: "8 min",
    publishedAtLabel: "5 février 2026",
    publishedAtIso: "2026-02-05",
    imageSrc: u("photo-1460925895917-afdab827c52f"),
    imageAlt: "Écran d’ordinateur affichant graphiques et analytics web",
    body: p(
      "Une refonte ne commence pas par la charte graphique mais par les objectifs : génération de leads, recrutement, support client self-service ou valorisation d’offres complexes ? Chaque choix UX en découle.",
      "Les contenus existants doivent être audités (SEO, doublons, pages zombies) avant migration : c’est souvent là que l’on gagne le plus en clarté et en positionnement.",
      "Côté technique, viser les Core Web Vitals et une structure de données propre facilite la mesure marketing et l’intégration avec votre CRM ou votre plateforme d’emailing.",
    ),
  },
  {
    slug: "mesurer-roi-campagnes-digitales-b2b",
    title: "Mesurer le ROI des campagnes digitales B2B sans se perdre dans les métriques",
    pole: "digital",
    excerpt:
      "Du clic à la signature : aligner Google Analytics, le CRM et la marge pour des décisions d’budget plus sereines.",
    seoDescription:
      "ROI marketing B2B : indicateurs utiles (CPL, conversion, cycle de vente), attribution multi-touch pragmatique et alignement Google Analytics / CRM pour arbitrer le budget digital.",
    keywords: [
      "ROI marketing B2B",
      "Google Analytics",
      "CRM",
      "attribution marketing",
      "campagnes digitales",
      "lead qualifié",
      "UTM",
      "tableau de bord marketing",
    ],
    readMinutes: "7 min",
    publishedAtLabel: "20 mars 2026",
    publishedAtIso: "2026-03-20",
    imageSrc: u("photo-1551288049-bebda4e38f71"),
    imageAlt: "Tableaux de bord et indicateurs sur écran",
    body: p(
      "Les équipes marketing accumulent les tableaux de bord ; la difficulté est d’isoler les indicateurs qui prédisent le chiffre d’affaires : coût par lead qualifié, taux de conversion étape par étape, cycle de vente moyen.",
      "L’attribution multi-touch reste un compromis : l’important est de figer une règle simple, comprise par la direction commerciale, plutôt que de viser la perfection statistique.",
      "En reliant les UTM, les formulaires et les étapes CRM, on peut enfin arbitrer entre contenu organique, paid search et événements terrain avec des chiffres comparables.",
    ),
  },
  {
    slug: "digital-seo-technique-2026",
    title: "SEO technique en 2026 : Core Web Vitals, canonical et indexation",
    pole: "digital",
    excerpt: "Crawl budget, JavaScript rendering et logs serveur : les priorités pour les grands sites B2B.",
    readMinutes: "6 min",
    publishedAtLabel: "7 février 2026",
    publishedAtIso: "2026-02-07",
    imageSrc: u("photo-1504868584819-f8e8b4b6d7e3"),
    imageAlt: "Recherche et référencement sur navigateur",
    body: p(
      "Les signaux de performance perçue restent des facteurs différenciants lorsque le contenu concurrent est dense.",
      "Les erreurs de canonicalisation et les paramètres d’URL inutiles gaspillent le crawl budget et diluent le PageRank interne.",
      "Analyser les logs serveur permet d’aligner la stratégie d’indexation sur ce que Googlebot explore réellement.",
    ),
  },
  {
    slug: "digital-storytelling-marque-b2b",
    title: "Storytelling de marque B2B : passer du jargon à la preuve",
    pole: "digital",
    excerpt: "Cas clients, chiffres et témoignages : structurer une narration crédible pour les cycles longs.",
    readMinutes: "5 min",
    publishedAtLabel: "14 février 2026",
    publishedAtIso: "2026-02-14",
    imageSrc: u("photo-1552664730-d307ca884978"),
    imageAlt: "Réunion créative en équipe",
    body: p(
      "Les acheteurs B2B valident en comité : votre storytelling doit adresser simultanément les utilisateurs, la finance et la DSI.",
      "Les formats « avant / après » chiffrés convertissent mieux que les adjectifs superlatifs non sourcés.",
      "Réutilisez les mêmes histoires sur le site, LinkedIn et les salles de comité en adaptant la densité technique.",
    ),
  },
  {
    slug: "digital-google-ads-b2b",
    title: "Google Ads B2B : structures de campagnes et audiences intent",
    pole: "digital",
    excerpt: "SKAG vs thèmes, audiences in-market et suivi offline des conversions.",
    readMinutes: "6 min",
    publishedAtLabel: "21 février 2026",
    publishedAtIso: "2026-02-21",
    imageSrc: u("photo-1460925895917-afdab827c52f"),
    imageAlt: "Campagne publicitaire et analytics",
    body: p(
      "Les structures trop fragmentées rendent l’optimisation impossible ; des groupes thématiques homogènes facilitent l’ajustement des enchères.",
      "Les audiences in-market et remarketing doivent être croisées avec des exclusions (concurrents, étudiants) pour préserver le CPL.",
      "Importez les conversions CRM pour entraîner les algorithmes sur la valeur réelle, pas seulement sur les leads bruts.",
    ),
  },
  {
    slug: "digital-meta-creatifs",
    title: "Meta Ads : itérer sur les créatifs sans épuiser votre audience",
    pole: "digital",
    excerpt: "Fatigue publicitaire, hooks courts et tests statistiques simples pour les équipes réduites.",
    readMinutes: "5 min",
    publishedAtLabel: "27 février 2026",
    publishedAtIso: "2026-02-27",
    imageSrc: u("photo-1611162616305-c69b3fa7fbe0"),
    imageAlt: "Réseaux sociaux et marketing mobile",
    body: p(
      "La diversité des formats (Reels, carrousels, statiques) prolonge la vie des campagnes sans multiplier les budgets.",
      "Un backlog de hooks vidéo de trois secondes permet de relancer rapidement les ensembles publicitaires en baisse.",
      "Fixez des critères d’arrêt clairs (fréquence max, CPC seuil) pour éviter les micro-optimisations infinies.",
    ),
  },
  {
    slug: "digital-emailing-delivrabilite",
    title: "Délivrabilité e-mail : SPF, DKIM, DMARC et réputation domaine",
    pole: "digital",
    excerpt: "Authentification, listes propres et segmentation : les bases souvent oubliées.",
    readMinutes: "6 min",
    publishedAtLabel: "6 mars 2026",
    publishedAtIso: "2026-03-06",
    imageSrc: u("photo-1563986768609-322da13575f3"),
    imageAlt: "Messagerie professionnelle",
    body: p(
      "DMARC en policy none puis quarantine permet de détecter les usages frauduleux avant de bloquer brutalement.",
      "Les listes non consenties détruisent la réputation IP/domaine plus vite que tout contenu perfectible.",
      "Segmentez les ouvertures et clics par engagement pour réactiver progressivement les inactifs plutôt que de tout supprimer.",
    ),
  },
  {
    slug: "digital-design-system-figma",
    title: "Design system : du Figma au front sans dette visuelle",
    pole: "digital",
    excerpt: "Tokens, composants et documentation vivante pour accélérer marketing et dev.",
    readMinutes: "6 min",
    publishedAtLabel: "13 mars 2026",
    publishedAtIso: "2026-03-13",
    imageSrc: u("photo-1561070791-2526d30994b5"),
    imageAlt: "Design interface utilisateur",
    body: p(
      "Sans tokens de couleur et d’espacement, chaque landing page recrée des marges légèrement différentes.",
      "Les composants Figma doivent refléter les props réelles du framework front pour éviter les écarts à l’intégration.",
      "Une documentation consultée (analytics interne) vaut mieux qu’une bibliothèque exhaustive jamais ouverte.",
    ),
  },
  {
    slug: "digital-accessibilite-rgaa",
    title: "Accessibilité RGAA : prioriser les quick wins sur les audits exhaustifs",
    pole: "digital",
    excerpt: "Contrastes, focus clavier et composants custom : où investir en premier.",
    readMinutes: "7 min",
    publishedAtLabel: "16 mars 2026",
    publishedAtIso: "2026-03-16",
    imageSrc: u("photo-1586717791821-3f44a563fa4c"),
    imageAlt: "Accessibilité numérique",
    body: p(
      "Les images décoratives sans alt et les boutons sans nom accessible sont parmi les défauts les plus fréquents et les plus simples à corriger.",
      "Les composants type carrousel ou modale nécessitent pièges de focus et annonces ARIA cohérentes.",
      "Intégrez l’accessibilité dans la définition de fini (« definition of done ») plutôt qu’en phase de recette unique.",
    ),
  },
  {
    slug: "digital-shopify-international",
    title: "Shopify international : devises, TVA et SEO hreflang",
    pole: "digital",
    excerpt: "Marchés, expérience checkout et duplication de contenus : une grille de décision.",
    readMinutes: "6 min",
    publishedAtLabel: "22 mars 2026",
    publishedAtIso: "2026-03-22",
    imageSrc: u("photo-1556742049-0cfed4f6a45d"),
    imageAlt: "E-commerce et shopping en ligne",
    body: p(
      "Les expansions B2C échouent souvent sur la logistique et la fiscalité, pas sur le thème visuel.",
      "Les balises hreflang mal croisées créent des doublons indexés entre pays linguistiques proches.",
      "Testez le checkout mobile sur les moyens de paiement locaux avant d’activer massivement les campagnes.",
    ),
  },
  {
    slug: "digital-content-hub-seo",
    title: "Content hub : organiser le SEO thématique sans cannibaliser ses pages",
    pole: "digital",
    excerpt: "Piliers, clusters et maillage interne pour les sites à fort catalogue éditorial.",
    readMinutes: "6 min",
    publishedAtLabel: "25 mars 2026",
    publishedAtIso: "2026-03-25",
    imageSrc: u("photo-1455390582262-044cdead277a"),
    imageAlt: "Rédaction et stratégie de contenu",
    body: p(
      "Un pilier trop large attire du trafic peu qualifié ; découpez par intention de recherche (informationnelle vs transactionnelle).",
      "Le maillage interne doit respecter une profondeur de clic raisonnable pour les pages feuilles.",
      "Mesurez la performance par cluster, pas seulement par URL isolée.",
    ),
  },
  {
    slug: "digital-cro-formulaires",
    title: "CRO des formulaires B2B : friction, confiance et pré-qualification",
    pole: "digital",
    excerpt: "Nombre de champs, preuves sociales et progressive profiling pour augmenter les demandes qualifiées.",
    readMinutes: "5 min",
    publishedAtLabel: "28 mars 2026",
    publishedAtIso: "2026-03-28",
    imageSrc: u("photo-1551434678-e076c223a692"),
    imageAlt: "Formulaire web sur ordinateur",
    body: p(
      "Chaque champ supplémentaire filtre… mais aussi fait fuir : mappez les données indispensables au SDR vs enrichissables en second temps.",
      "Les micro-copy de confidentialité près du bouton d’envoi réduisent l’anxiété sur l’usage des données.",
      "A/B testez une seule hypothèse à la fois pour isoler les effets.",
    ),
  },
  {
    slug: "digital-linkedin-organique",
    title: "LinkedIn organique : calendrier éditorial et formats natifs",
    pole: "digital",
    excerpt: "Document carrousel, newsletter et commentaires : bâtir une autorité sans budget pub.",
    readMinutes: "5 min",
    publishedAtLabel: "1 avril 2026",
    publishedAtIso: "2026-04-01",
    imageSrc: u("photo-1522071820081-009f0129c71c"),
    imageAlt: "Réseau professionnel et collaboration",
    body: p(
      "Les PDF statiques convertis en carrousels natifs gagnent souvent en portée grâce au format.",
      "Les prises de position mesurées sur les sujets sectoriels fonctionnent mieux que le corporate speak neutre.",
      "Répondez aux commentaires dans les deux heures pour favoriser l’amplification algorithmique.",
    ),
  },
  {
    slug: "digital-video-courte-b2b",
    title: "Vidéo courte B2B : scripts, sous-titres et CTA sans casser le rythme",
    pole: "digital",
    excerpt: "Hooks, preuves et appel à l’action en moins de quarante secondes pour les feeds.",
    readMinutes: "5 min",
    publishedAtLabel: "4 avril 2026",
    publishedAtIso: "2026-04-04",
    imageSrc: u("photo-1492691527719-9d1e07e534b4"),
    imageAlt: "Production vidéo",
    body: p(
      "Le premier plan doit annoncer le bénéfice métier, pas le logo d’entreprise.",
      "Les sous-titres brûlés incrustés améliorent la rétention sur mobile en consultation silencieuse.",
      "Un seul CTA clair évite la dilution ; renvoyez vers une landing dédiée plutôt que la home générique.",
    ),
  },
  {
    slug: "digital-cmp-consent-mode",
    title: "CMP & Consent Mode : mesurer le marketing sans biaiser les données",
    pole: "digital",
    excerpt: "Modélisation, tags serveur et documentation juridique : l’alignement marketing / juridique.",
    readMinutes: "7 min",
    publishedAtLabel: "8 avril 2026",
    publishedAtIso: "2026-04-08",
    imageSrc: u("photo-1563986768609-322da13575f3"),
    imageAlt: "Conformité et données personnelles",
    body: p(
      "Le consent mode v2 impose de revoir les flux GA4 et Ads pour éviter les mesures tronquées silencieusement.",
      "Le server-side tagging améliore la qualité des données tout en réduisant la surface des trackers côté client.",
      "Documentez les finalités et les bases légales pour chaque outil marketing branché au site.",
    ),
  },
  // --- Solutions (15) ---
  {
    slug: "videosurveillance-rgpd-entreprise",
    title: "Vidéosurveillance en entreprise et RGPD : rappel des bases",
    pole: "solutions",
    excerpt:
      "Finalité, durée de conservation, information des personnes et accès aux enregistrements : ce que dit le cadre français.",
    readMinutes: "6 min",
    publishedAtLabel: "18 février 2026",
    publishedAtIso: "2026-02-18",
    imageSrc: u("photo-1587825140708-dfaf72ae4b04"),
    imageAlt: "Caméra de surveillance moderne sur façade de bâtiment",
    body: p(
      "La vidéosurveillance sur le lieu de travail doit répondre à une finalité précise (sécurité des biens et des personnes, contrôle d’accès) et être proportionnée : on évite les angles qui filment des espaces de détente ou des circulations sans lien avec le risque.",
      "Les personnes filmées doivent être informées par affichage lisible ; les enregistrements sont conservés pour une durée limitée, en principe trente jours sauf justification particulière.",
      "Les accès aux images doivent être tracés et réservés aux personnes habilitées ; en cas d’incident, la coopération avec l’autorité compétente s’appuie sur des procédures préalablement documentées.",
    ),
  },
  {
    slug: "reseau-lan-wifi-entreprise-fiabilite",
    title: "Réseau LAN et Wi-Fi en entreprise : viser la fiabilité avant la vitesse affichée",
    pole: "solutions",
    excerpt:
      "Qualité de câblage, dimensionnement des points d’accès et supervision proactive : les leviers souvent négligés.",
    readMinutes: "5 min",
    publishedAtLabel: "3 mars 2026",
    publishedAtIso: "2026-03-03",
    imageSrc: u("photo-1544197150-b99a580bb7a8"),
    imageAlt: "Serveurs rackés dans une salle technique",
    body: p(
      "Un débit Wi-Fi annoncé sur la boîte du routeur ne dit rien de l’expérience réelle en open space : la densité d’utilisateurs, les cloisons et les interférences Bluetooth ou micro-ondes dégradent fortement le signal.",
      "Un audit radio et un plan de positionnement des AP, parfois complété d’Ethernet filaire pour les postes critiques, restent la base d’un réseau stable.",
      "La supervision (SNMP, sondes, alertes) permet d’anticiper la saturation des liens et les pannes matérielles avant qu’elles n’impactent la production ou la VoIP.",
    ),
  },
  {
    slug: "solutions-controle-acces-biometrie",
    title: "Contrôle d’accès biométrique : conformité CNIL et alternatives",
    pole: "solutions",
    excerpt: "Empreinte, reconnaissance veineuse ou badge : arbitrer risque, UX et cadre juridique.",
    readMinutes: "6 min",
    publishedAtLabel: "9 mars 2026",
    publishedAtIso: "2026-03-09",
    imageSrc: u("photo-1563986768609-322da13575f3"),
    imageAlt: "Lecteur de badge et sécurité d’accès",
    body: p(
      "La biométrie est une donnée sensible : la finalité doit être strictement nécessaire et les alternatives (badge + PIN) documentées.",
      "Les lecteurs veineux ou faciaux doivent être configurés pour limiter la conservation des templates et sécuriser les transferts.",
      "Prévoyez une procédure de secours en cas de panne lecteur pour éviter le blocage des issues de secours.",
    ),
  },
  {
    slug: "solutions-detection-incendie-ess",
    title: "SSI : centrale adressable vs conventionnelle pour le tertiaire",
    pole: "solutions",
    excerpt: "Évolutivité, localisation précise des défauts et maintenance : le comparatif terrain.",
    readMinutes: "6 min",
    publishedAtLabel: "15 mars 2026",
    publishedAtIso: "2026-03-15",
    imageSrc: u("photo-1581092918056-0c4c3acd3789"),
    imageAlt: "Installation industrielle et sécurité",
    body: p(
      "L’adressable réduit les fausses alertes grâce à la distinction alarme / dérangement par point.",
      "Le conventionnel reste pertinent sur des petits sites peu dynamiques où le coût au point prime.",
      "La maintenance réglementaire ne remplace pas la formation des occupants aux consignes en cas de déclenchement.",
    ),
  },
  {
    slug: "solutions-cctv-low-light",
    title: "Vidéo basse lumière : capteurs, lentilles et compression intelligente",
    pole: "solutions",
    excerpt: "Scènes nocturnes, parkings et entrepôts : optimiser la preuve sans surdimensionner le stockage.",
    readMinutes: "5 min",
    publishedAtLabel: "19 mars 2026",
    publishedAtIso: "2026-03-19",
    imageSrc: u("photo-1587825140708-dfaf72ae4b04"),
    imageAlt: "Caméra de surveillance",
    body: p(
      "Les grandes ouvertures optiques et les capteurs grand pixel améliorent le SNR lorsque l’éclairage est faible.",
      "Le H.265+ ou équivalent réduit le bitrate sur les zones statiques tout en préservant le détail sur les mouvements.",
      "Évitez les angles trop larges qui diluent les pixels par mètre sur les visages à identifier.",
    ),
  },
  {
    slug: "solutions-intrusion-grands-batiments",
    title: "Intrusion volumétrique : zoner les grandes surfaces commerciales",
    pole: "solutions",
    excerpt: "Partitions, temporisations et gestion des ouvertures pour limiter les nuisances.",
    readMinutes: "5 min",
    publishedAtLabel: "23 mars 2026",
    publishedAtIso: "2026-03-23",
    imageSrc: u("photo-1604719312566-8912e9227c6a"),
    imageAlt: "Grande surface et sécurité",
    body: p(
      "Les zones logistiques nécessitent souvent des détecteurs double technologie pour éviter les fausses alarmes liées à la chaleur furtive.",
      "Les temporisations d’entrée/sortie doivent être cohérentes avec les procédures d’ouverture réelles des équipes.",
      "La télésurveillance doit recevoir des clips contextualisés, pas seulement une alarme générique.",
    ),
  },
  {
    slug: "solutions-baie-courant-faible",
    title: "Baies brassage : repères, étiquetage et évolutivité du câblage",
    pole: "solutions",
    excerpt: "T568A/B, couleurs par service et documentation pour accélérer les interventions.",
    readMinutes: "5 min",
    publishedAtLabel: "27 mars 2026",
    publishedAtIso: "2026-03-27",
    imageSrc: u("photo-1544197150-b99a580bb7a8"),
    imageAlt: "Baie de brassage réseau",
    body: p(
      "Un plan de repérage stable évite les erreurs de patching lors des ajouts de caméras ou de points Wi-Fi.",
      "Réservez des guides-câbles et des passe-câbles pour les extensions sans refonte complète.",
      "Photographiez l’état « propre » après recette pour former les équipes d’exploitation.",
    ),
  },
  {
    slug: "solutions-sonorisation-evac",
    title: "Sonorisation & EVAC : intelligibilité et priorité micro",
    pole: "solutions",
    excerpt: "Mesures STI, zones acoustiques et scénarios feu pour sites publics.",
    readMinutes: "6 min",
    publishedAtLabel: "29 mars 2026",
    publishedAtIso: "2026-03-29",
    imageSrc: u("photo-1504307651254-35680f356dfd"),
    imageAlt: "Système audio et événementiel",
    body: p(
      "L’intelligibilité prime sur le volume brut : les enceintes doivent être réparties pour couvrir les zones d’attente denses.",
      "Les priorités micro (fireman mic) doivent être testées lors des exercices annuels, pas seulement à la réception.",
      "Les boucles induction magnétique complètent l’accessibilité pour malentendants dans les halls.",
    ),
  },
  {
    slug: "solutions-portier-video-ip",
    title: "Portier vidéo IP : intégration mobile et résilience en cas de panne",
    pole: "solutions",
    excerpt: "SIP, cloud et alimentation PoE : check-list pour copropriétés et sièges.",
    readMinutes: "5 min",
    publishedAtLabel: "2 avril 2026",
    publishedAtIso: "2026-04-02",
    imageSrc: u("photo-1600607687939-ce8a6c25118c"),
    imageAlt: "Architecture résidentielle moderne",
    body: p(
      "Le SIP vers standard mobile évite les applications propriétaires fermées, au prix d’une configuration DNS/TLS rigoureuse.",
      "Les alimentations PoE doivent être dimensionnées pour les pics de courant hivernaux des portes motorisées.",
      "Prévoyez un mode dégradé (sonnerie secours) si le lien internet tombe.",
    ),
  },
  {
    slug: "solutions-vms-federation",
    title: "VMS fédérés : centraliser la vue sans tout passer par le cloud",
    pole: "solutions",
    excerpt: "Enregistreurs locaux, streaming et droits utilisateurs hiérarchisés.",
    readMinutes: "6 min",
    publishedAtLabel: "5 avril 2026",
    publishedAtIso: "2026-04-05",
    imageSrc: u("photo-1587825140708-dfaf72ae4b04"),
    imageAlt: "Salle de contrôle vidéo",
    body: p(
      "La fédération permet au siège de consulter les sites distants sans dupliquer tous les flux en continu.",
      "Les profils utilisateurs doivent coller aux rôles métiers (sûreté, RH, maintenance) avec journalisation.",
      "La bande passante WAN doit être chiffrée et priorisée pour éviter l’impact sur la VoIP.",
    ),
  },
  {
    slug: "solutions-onvif-profiles",
    title: "ONVIF : profils S, T et G pour l’interopérabilité caméras / VMS",
    pole: "solutions",
    excerpt: "Découverte automatique, événements et accès sécurisé aux flux RTSP.",
    readMinutes: "5 min",
    publishedAtLabel: "7 avril 2026",
    publishedAtIso: "2026-04-07",
    imageSrc: u("photo-1587825140708-dfaf72ae4b04"),
    imageAlt: "Caméras réseau",
    body: p(
      "Les profils récents sécurisent mieux les flux que les implémentations RTSP basiques par défaut fabricant.",
      "Validez en recette que les événements analytics (ligne virtuelle, détection de présence) remontent bien côté VMS.",
      "Documentez les versions firmware supportées pour éviter les mises à jour cassantes en série.",
    ),
  },
  {
    slug: "solutions-alarme-perimetrique",
    title: "Alarme périmétrique : barrières IR et détection sur clôtures",
    pole: "solutions",
    excerpt: "Faux positifs animaux, météo et intégration télésurveillance.",
    readMinutes: "5 min",
    publishedAtLabel: "9 avril 2026",
    publishedAtIso: "2026-04-09",
    imageSrc: u("photo-1504307651254-35680f356dfd"),
    imageAlt: "Site industriel sécurisé",
    body: p(
      "Le réglage des sensibilités doit être fait sur plusieurs saisons pour éviter les déclenchements pluie/vent.",
      "Les barrières doivent être alimentées et supervisées secteur par secteur pour limiter les zones aveugles.",
      "Couplez détection périmétrique et vidéo analytique pour réduire les interventions inutiles.",
    ),
  },
  {
    slug: "solutions-datacenter-courants-faibles",
    title: "Datacenter : courants faibles, chemins de câbles et séparation forte/faible",
    pole: "solutions",
    excerpt: "EMC, goulottes et accès contrôlés pour salles blanches modulaires.",
    readMinutes: "6 min",
    publishedAtLabel: "10 avril 2026",
    publishedAtIso: "2026-04-10",
    imageSrc: u("photo-1558494949-ef010cbdcc31"),
    imageAlt: "Infrastructure datacenter",
    body: p(
      "La séparation physique des chemins CFa et CFo réduit les risques de perturbations sur les liaisons fibre.",
      "Les trappes et accès doivent être logués et couplés au contrôle d’accès physique.",
      "Prévoyez des réserves de goulottes pour l’ajout futur de capteurs environnementaux.",
    ),
  },
  {
    slug: "solutions-domotique-tertiaire",
    title: "GTB légère en tertiaire : scénarios d’éclairage et présence",
    pole: "solutions",
    excerpt: "Capteurs CO₂, présence et intégration BMS pour le confort et l’énergie.",
    readMinutes: "5 min",
    publishedAtLabel: "11 avril 2026",
    publishedAtIso: "2026-04-11",
    imageSrc: u("photo-1497366216548-37526070297c"),
    imageAlt: "Bureau connecté",
    body: p(
      "Les scénarios doivent rester compréhensibles par les facility managers sans ingénierie à chaque changement d’étage.",
      "Les capteurs CO₂ aident à la ventilation dynamique mais nécessitent étalonnage et entretien filtres.",
      "Évitez la sur-automatisation qui dégrade l’expérience utilisateur (oscillations d’éclairage).",
    ),
  },
  {
    slug: "solutions-maintenance-preventive",
    title: "Maintenance préventive sûreté : planning et indicateurs terrain",
    pole: "solutions",
    excerpt: "GTR, pièces critiques et reporting digital pour les multi-sites.",
    readMinutes: "5 min",
    publishedAtLabel: "12 avril 2026",
    publishedAtIso: "2026-04-12",
    imageSrc: u("photo-1581092918056-0c4c3acd3789"),
    imageAlt: "Technicien en intervention",
    body: p(
      "Les visites planifiées doivent couvrir batteries, alimentations et versions firmware, pas seulement le essai sirène.",
      "Un stock mini de détecteurs / sirènes au siège réduit le GTR sur sites éloignés.",
      "Digitalisez les rapports avec photos horodatées pour tracer l’état des installations.",
    ),
  },
];
